[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "huggingface-hub>=2.1.1",
    "llama-cpp-python>=0.3.36",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
    "unstructured[md]>=0.27.10",
    "uvicorn>=0.54.0",
]

[project.scripts]
jarvis = "jarvis:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
